import { webcrypto } from 'node:crypto';
import { createCachedSigningKeyProvider, type SigningKeyProvider } from '@maronn-openid-connect/core';
import { FirestoreJtiStore, createFirestoreDocumentStore } from '@xaa/gcp';
import createHumanIdp from '@xaa/human-idp/app';
import type { HumanIdpEnv } from '@xaa/human-idp/src/env';
import { deriveIdpKid } from '@xaa/human-idp/src/keys/self-bootstrap';
import { createHumanIdpStores } from '@xaa/human-idp/src/store/provider-stores';
import { publishable } from '../local/jwks.js';
import { listen, type Listener } from '../local/serve.js';
import type { LocalPlatform } from '../platform.js';

/**
 * The SSO signing key.
 *
 * DEC-ID-17 keeps this key out of KMS even on GCP — core's `SigningKeyProvider` wants a
 * `CryptoKey`, so the private half is generated by the service, wrapped with a KMS key
 * and stored in a bucket. Here the wrap and the bucket are gone and the generation is
 * not: it is the same RSA-2048 key, with the same `idp-<thumbprint>` kid, published
 * into the same aggregate JWK Set that every verifier in the platform reads.
 */
async function localSsoKey(platform: LocalPlatform): Promise<SigningKeyProvider> {
  const pair = await webcrypto.subtle.generateKey(
    { name: 'RSASSA-PKCS1-v1_5', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' },
    true, ['sign', 'verify'],
  );
  const publicJwk = await webcrypto.subtle.exportKey('jwk', pair.publicKey);
  const kid = await deriveIdpKid(publicJwk);
  platform.jwks.publish(publishable(publicJwk, kid, 'RS256'));
  const key = { privateKey: pair.privateKey, publicJwk: { ...publicJwk, kid, alg: 'RS256', use: 'sig' }, keyId: kid };
  return createCachedSigningKeyProvider({
    async getSigningKey() { return key; },
    async getSigningKeys() { return [key]; },
  }, 300_000);
}

export function humanIdpEnvironment(platform: LocalPlatform): HumanIdpEnv {
  const { url } = platform.config.topology;
  return {
    port: 0,
    issuer: url['human-idp'],
    issuerProfile: 'direct',
    jwksBucket: 'local-jwks',
    // What the discovery document advertises as `jwks_uri`. The issuer's own endpoint,
    // because that is the set a client of this IdP verifies its ID Token against; the
    // platform's aggregate set is a different document with a different reader.
    jwksPublicBaseUrl: `${url['human-idp']}/.well-known`,
    keyBucket: 'local-platform-config',
    kmsSsoKeyName: platform.keys.humanIdpSso,
    signerMode: 'local',
    // Not `gcp`: the value gates the http-redirect-URI guard in `config/clients.ts`,
    // and a local deployment is exactly the case that guard exempts.
    storeMode: 'emulator',
    firestoreDatabase: 'xaa-db',
    dpopRequired: true,
    clientSecretAutomationApp: platform.secrets.automationApp,
    clientSecretAgentPlatform: platform.secrets.agentPlatform,
    clientSecretAnalysisConsole: platform.secrets.analysisConsole,
    automationAppRedirectUri: `${url['automation-app']}/callback`,
    agentOpCallbackUri: `${url['agent-op-callback']}/xaa/callback`,
    analysisConsoleRedirectUri: `${url['analysis-console']}/callback`,
    // The same 3600 the deployment sets, and for the same reason: a token shorter than
    // the Automation App's session is a session that stops working while still valid.
    accessTokenExpiresIn: 3600,
  };
}

export async function startHumanIdp(platform: LocalPlatform): Promise<Listener> {
  const env = humanIdpEnvironment(platform);
  const documents = createFirestoreDocumentStore(platform.firestore, 'human-idp');
  const app = createHumanIdp({
    env,
    stores: createHumanIdpStores(documents).stores,
    jtiStore: new FirestoreJtiStore(platform.firestore),
    signingKeyProvider: await localSsoKey(platform),
  });
  return listen({
    name: 'human-idp',
    host: platform.config.topology.host,
    port: platform.config.topology.port['human-idp'],
    fetch: (request) => app.fetch(request),
  });
}
