import { createCachedSigningKeyProvider, type SigningKeyProvider } from '@maronn-openid-connect/core';
import { FirestoreJtiStore, createFirestoreDocumentStore } from '@xaa/gcp';
import createHumanIdp from '@xaa/human-idp/app';
import type { HumanIdpEnv } from '@xaa/human-idp/src/env';
import { bootstrapSigningKey } from '@xaa/human-idp/src/keys/self-bootstrap';
import { createHumanIdpStores } from '@xaa/human-idp/src/store/provider-stores';
import { publishable } from '../local/jwks.js';
import { createLocalEnvelope } from '../local/kms.js';
import { createLocalObjectStore } from '../local/object-store.js';
import { listen, type Listener } from '../local/serve.js';
import type { LocalPlatform } from '../platform.js';

/**
 * The SSO signing key.
 *
 * DEC-ID-17 keeps this key out of KMS even on GCP — core's `SigningKeyProvider` wants a
 * `CryptoKey`, so the private half is generated by the service, wrapped with a KMS key
 * and stored in a bucket. That is `bootstrapSigningKey`, and it is the deployed code,
 * called here with the local KMS underneath the wrap and the state directory underneath
 * the bucket. A run that finds the object reads the same key back; a run with no state
 * to read makes one, exactly as the first cold start on GCP does.
 *
 * Reading it back is what makes a login outlive a restart. The Access Tokens in a
 * person's browser are signed with this key, and a platform that generated a new one on
 * every start would answer every one of them with a signature it cannot verify.
 *
 * The publish is unconditional because the aggregate JWK Set is not the bucket: on GCP
 * `jwks-publish` merges the stored key objects into the served document, and here that
 * merge is this line.
 */
async function localSsoKey(platform: LocalPlatform): Promise<SigningKeyProvider> {
  const bootstrapped = await bootstrapSigningKey({
    store: platform.state.objects,
    envelope: createLocalEnvelope(platform.kms, platform.keys.humanIdpSso),
    // Nowhere to write to: the published set is built from what comes back below.
    jwksStore: createLocalObjectStore(),
  });
  platform.jwks.publish(publishable(bootstrapped.publicJwk, bootstrapped.kid, 'RS256'));
  const key = {
    privateKey: bootstrapped.privateKey,
    publicJwk: { ...bootstrapped.publicJwk, kid: bootstrapped.kid, alg: 'RS256', use: 'sig' },
    keyId: bootstrapped.kid,
  };
  return createCachedSigningKeyProvider({
    async getSigningKey() { return key; },
    async getSigningKeys() { return [key]; },
  }, 300_000);
}

export function humanIdpEnvironment(platform: LocalPlatform): HumanIdpEnv {
  const { url } = platform.config.topology;
  return {
    port: 0,
    issuer: url['human-idp'],
    issuerProfile: 'direct',
    jwksBucket: 'local-jwks',
    // What the discovery document advertises as `jwks_uri`. The issuer's own endpoint,
    // because that is the set a client of this IdP verifies its ID Token against; the
    // platform's aggregate set is a different document with a different reader.
    jwksPublicBaseUrl: `${url['human-idp']}/.well-known`,
    keyBucket: 'local-platform-config',
    kmsSsoKeyName: platform.keys.humanIdpSso,
    signerMode: 'local',
    // Not `gcp`: the value gates the http-redirect-URI guard in `config/clients.ts`,
    // and a local deployment is exactly the case that guard exempts.
    storeMode: 'emulator',
    firestoreDatabase: 'xaa-db',
    dpopRequired: true,
    clientSecretAutomationApp: platform.secrets.automationApp,
    clientSecretAgentPlatform: platform.secrets.agentPlatform,
    clientSecretAnalysisConsole: platform.secrets.analysisConsole,
    automationAppRedirectUri: `${url['automation-app']}/callback`,
    agentOpCallbackUri: `${url['agent-op-callback']}/xaa/callback`,
    analysisConsoleRedirectUri: `${url['analysis-console']}/callback`,
    // The same 3600 the deployment sets, and for the same reason: a token shorter than
    // the Automation App's session is a session that stops working while still valid.
    accessTokenExpiresIn: 3600,
  };
}

export async function startHumanIdp(platform: LocalPlatform): Promise<Listener> {
  const env = humanIdpEnvironment(platform);
  const documents = createFirestoreDocumentStore(platform.firestore, 'human-idp');
  const app = createHumanIdp({
    env,
    stores: createHumanIdpStores(documents).stores,
    jtiStore: new FirestoreJtiStore(platform.firestore),
    signingKeyProvider: await localSsoKey(platform),
  });
  return listen({
    name: 'human-idp',
    host: platform.config.topology.host,
    port: platform.config.topology.port['human-idp'],
    fetch: (request) => app.fetch(request),
  });
}
